// <auto-generated />
using System;
using FinalProject_201810088.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FinalProject_201810088.Migrations
{
    [Migration("20220117232946_EditSeedData")]
    partial class EditSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FinalProject_201810088.Models.Drawer", b =>
                {
                    b.Property<int>("DrawerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("CostPerManga")
                        .HasColumnType("float");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DrawerId");

                    b.ToTable("Drawers");

                    b.HasData(
                        new
                        {
                            DrawerId = 1,
                            CostPerManga = 120.0,
                            EmailAddress = "Drawer1@gmail.com",
                            Name = "Drawer 1",
                            PhoneNumber = "+962779783215",
                            ProfilePicture = "/Images/Drawer"
                        },
                        new
                        {
                            DrawerId = 2,
                            CostPerManga = 70.0,
                            EmailAddress = "Drawer2@gmail.com",
                            Name = "Drawer 2",
                            PhoneNumber = "+962779783220",
                            ProfilePicture = "/Images/Drawer"
                        },
                        new
                        {
                            DrawerId = 3,
                            CostPerManga = 35.0,
                            EmailAddress = "Drawer3@gmail.com",
                            Name = "Drawer 3",
                            PhoneNumber = "+962779783235",
                            ProfilePicture = "/Images/Drawer"
                        },
                        new
                        {
                            DrawerId = 4,
                            CostPerManga = 40.0,
                            EmailAddress = "Drawer4@gmail.com",
                            Name = "Drawer 4",
                            PhoneNumber = "+962779783240",
                            ProfilePicture = "/Images/Drawer"
                        },
                        new
                        {
                            DrawerId = 5,
                            CostPerManga = 55.0,
                            EmailAddress = "Drawer5@gmail.com",
                            Name = "Drawer 5",
                            PhoneNumber = "+962779783255",
                            ProfilePicture = "/Images/Drawer"
                        });
                });

            modelBuilder.Entity("FinalProject_201810088.Models.Manga", b =>
                {
                    b.Property<int>("MangaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("CoverImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NoOfEpisodes")
                        .HasColumnType("int");

                    b.HasKey("MangaId");

                    b.ToTable("Mangas");

                    b.HasData(
                        new
                        {
                            MangaId = 1,
                            Description = "it is a 24 Episodes anime",
                            Name = "Manga 1",
                            NoOfEpisodes = 24
                        },
                        new
                        {
                            MangaId = 2,
                            Description = "it is a 32 Episodes anime",
                            Name = "Manga 2",
                            NoOfEpisodes = 32
                        },
                        new
                        {
                            MangaId = 3,
                            Description = "it is a 40 Episodes anime",
                            Name = "Manga 3",
                            NoOfEpisodes = 40
                        },
                        new
                        {
                            MangaId = 4,
                            Description = "it is a 60 Episodes anime",
                            Name = "Manga 4",
                            NoOfEpisodes = 60
                        },
                        new
                        {
                            MangaId = 5,
                            Description = "it is a 12 Episodes anime",
                            Name = "Manga 5",
                            NoOfEpisodes = 12
                        });
                });

            modelBuilder.Entity("FinalProject_201810088.Models.Work", b =>
                {
                    b.Property<int>("WorkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AirsAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DrawerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MangaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("WorkId");

                    b.HasIndex("DrawerId");

                    b.HasIndex("MangaId");

                    b.ToTable("Works");

                    b.HasData(
                        new
                        {
                            WorkId = 1,
                            AirsAt = new DateTime(2022, 1, 18, 6, 29, 44, 804, DateTimeKind.Local).AddTicks(5845),
                            DrawerId = 1,
                            EndDate = new DateTime(2022, 1, 16, 1, 29, 44, 804, DateTimeKind.Local).AddTicks(5044),
                            MangaId = 1,
                            StartDate = new DateTime(2022, 1, 11, 1, 29, 44, 791, DateTimeKind.Local).AddTicks(8908),
                            Status = 0
                        },
                        new
                        {
                            WorkId = 2,
                            AirsAt = new DateTime(2022, 1, 18, 9, 29, 44, 804, DateTimeKind.Local).AddTicks(7361),
                            DrawerId = 2,
                            EndDate = new DateTime(2022, 1, 20, 1, 29, 44, 804, DateTimeKind.Local).AddTicks(7355),
                            MangaId = 2,
                            StartDate = new DateTime(2022, 1, 17, 1, 29, 44, 804, DateTimeKind.Local).AddTicks(7332),
                            Status = 2
                        },
                        new
                        {
                            WorkId = 3,
                            AirsAt = new DateTime(2022, 1, 17, 22, 29, 44, 804, DateTimeKind.Local).AddTicks(7375),
                            DrawerId = 3,
                            EndDate = new DateTime(2022, 1, 28, 1, 29, 44, 804, DateTimeKind.Local).AddTicks(7371),
                            MangaId = 3,
                            StartDate = new DateTime(2022, 1, 25, 1, 29, 44, 804, DateTimeKind.Local).AddTicks(7366),
                            Status = 1
                        },
                        new
                        {
                            WorkId = 4,
                            AirsAt = new DateTime(2022, 1, 18, 3, 29, 44, 804, DateTimeKind.Local).AddTicks(7387),
                            DrawerId = 3,
                            EndDate = new DateTime(2022, 2, 2, 1, 29, 44, 804, DateTimeKind.Local).AddTicks(7383),
                            MangaId = 1,
                            StartDate = new DateTime(2022, 1, 25, 1, 29, 44, 804, DateTimeKind.Local).AddTicks(7379),
                            Status = 0
                        },
                        new
                        {
                            WorkId = 5,
                            AirsAt = new DateTime(2022, 1, 18, 2, 29, 44, 804, DateTimeKind.Local).AddTicks(7404),
                            DrawerId = 1,
                            EndDate = new DateTime(2022, 2, 2, 1, 29, 44, 804, DateTimeKind.Local).AddTicks(7395),
                            MangaId = 3,
                            StartDate = new DateTime(2022, 1, 13, 1, 29, 44, 804, DateTimeKind.Local).AddTicks(7391),
                            Status = 1
                        },
                        new
                        {
                            WorkId = 6,
                            AirsAt = new DateTime(2022, 1, 18, 5, 29, 44, 804, DateTimeKind.Local).AddTicks(7416),
                            DrawerId = 4,
                            EndDate = new DateTime(2022, 2, 1, 1, 29, 44, 804, DateTimeKind.Local).AddTicks(7412),
                            MangaId = 4,
                            StartDate = new DateTime(2022, 1, 11, 1, 29, 44, 804, DateTimeKind.Local).AddTicks(7408),
                            Status = 1
                        },
                        new
                        {
                            WorkId = 7,
                            AirsAt = new DateTime(2022, 1, 18, 8, 29, 44, 804, DateTimeKind.Local).AddTicks(7427),
                            DrawerId = 5,
                            EndDate = new DateTime(2022, 1, 21, 1, 29, 44, 804, DateTimeKind.Local).AddTicks(7423),
                            MangaId = 4,
                            StartDate = new DateTime(2022, 1, 16, 1, 29, 44, 804, DateTimeKind.Local).AddTicks(7420),
                            Status = 2
                        },
                        new
                        {
                            WorkId = 8,
                            AirsAt = new DateTime(2022, 1, 18, 6, 29, 44, 804, DateTimeKind.Local).AddTicks(7439),
                            DrawerId = 1,
                            EndDate = new DateTime(2022, 1, 15, 1, 29, 44, 804, DateTimeKind.Local).AddTicks(7435),
                            MangaId = 5,
                            StartDate = new DateTime(2022, 1, 10, 1, 29, 44, 804, DateTimeKind.Local).AddTicks(7431),
                            Status = 0
                        });
                });

            modelBuilder.Entity("FinalProject_201810088.Models.Work", b =>
                {
                    b.HasOne("FinalProject_201810088.Models.Drawer", "Drawer")
                        .WithMany("Works")
                        .HasForeignKey("DrawerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinalProject_201810088.Models.Manga", "Manga")
                        .WithMany("Works")
                        .HasForeignKey("MangaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drawer");

                    b.Navigation("Manga");
                });

            modelBuilder.Entity("FinalProject_201810088.Models.Drawer", b =>
                {
                    b.Navigation("Works");
                });

            modelBuilder.Entity("FinalProject_201810088.Models.Manga", b =>
                {
                    b.Navigation("Works");
                });
#pragma warning restore 612, 618
        }
    }
}
